# Travis-CI Build for rabbitmq-c
# see travis-ci.org for details

# As CMake is not officially supported we use erlang VMs
language: c

compiler:
  - gcc

# Settings to try
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "gDwqo3jHj+HHGzFKnxL/nwZhbVeh2pItw0TbeaHcLtWubUZaf85ViEQRaXPyfnbG7l0OEQq+PjyhKAfvViVq2NP0lGeeu4VM5uMZJhsCLN594BJr39Y4XzOapg0O8mEMhQ0DU2u1Zo4LMgEcRz67aosVQOj6QV30tOzp9fnxn9U="
  matrix:
   - BUILD_SYSTEM=cmake

# Make sure CMake is installed
install:
  - sudo apt-get install cmake libpopt-dev

before_script:
  - mkdir _build
  - cd _build

# Run the Build script
script:
  - go run scripts/build.go

# Run Tests
after_script:
- if [ -f CTestTestfile.cmake ]; then ctest -V . ; fi

addons:
  coverity_scan:
    project:
      name: "alanxz/rabbitmq-c"
      description: "C AMQP client for RabbitMQ"
    notification_email: alan.antonuk@gmail.com
    build_command_prepend: cmake ..
    build_command: cmake --build .
    branch_pattern: coverity_scan
